name: Guilds
version: '${project.version}'
main: com.mineledge.guilds.Guilds
description: Guilds
api-version: '1.21.1'
folia-supported: true

commands:
  guild:
    description: Guilds base command.
    usage: /<command>
    permission: guilds.guild